2019-12-19 06:18:38,786-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:18:39,019-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:18:49,033-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.241.78.128', port=8010): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9268D90>, 'Connection to 223.241.78.128 timed out. (connect timeout=10)'))
2019-12-19 06:19:00,390-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='115.219.108.241', port=8010): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD0C10>, 'Connection to 115.219.108.241 timed out. (connect timeout=10)'))
2019-12-19 06:19:10,404-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='36.248.132.124', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD0CA0>, 'Connection to 36.248.132.124 timed out. (connect timeout=10)'))
2019-12-19 06:19:20,421-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.166.132.121', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3AF0>, 'Connection to 183.166.132.121 timed out. (connect timeout=10)'))
2019-12-19 06:19:22,652-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='60.167.103.218', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206C9AEF9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:19:32,665-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='60.167.135.148', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AEFFA0>, 'Connection to 60.167.135.148 timed out. (connect timeout=10)'))
2019-12-19 06:19:42,681-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.166.133.73', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3B80>, 'Connection to 183.166.133.73 timed out. (connect timeout=10)'))
2019-12-19 06:19:52,693-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='222.190.163.232', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD0E20>, 'Connection to 222.190.163.232 timed out. (connect timeout=10)'))
2019-12-19 06:20:02,706-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.24.232', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AEA7C0>, 'Connection to 223.198.24.232 timed out. (connect timeout=10)'))
2019-12-19 06:20:12,723-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.95.110.220', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD0AC0>, 'Connection to 117.95.110.220 timed out. (connect timeout=10)'))
2019-12-19 06:20:15,150-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.17.48', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206C9AE3820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:20:28,519-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='121.226.188.204', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C92A76D0>, 'Connection to 121.226.188.204 timed out. (connect timeout=10)'))
2019-12-19 06:20:38,539-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.69.151.243', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3BE0>, 'Connection to 117.69.151.243 timed out. (connect timeout=10)'))
2019-12-19 06:20:48,557-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='182.35.86.60', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD08E0>, 'Connection to 182.35.86.60 timed out. (connect timeout=10)'))
2019-12-19 06:20:58,577-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.19.93', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD0250>, 'Connection to 223.198.19.93 timed out. (connect timeout=10)'))
2019-12-19 06:21:08,597-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='27.152.8.152', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE31F0>, 'Connection to 27.152.8.152 timed out. (connect timeout=10)'))
2019-12-19 06:21:19,974-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='114.239.29.173', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3520>, 'Connection to 114.239.29.173 timed out. (connect timeout=10)'))
2019-12-19 06:21:22,190-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='114.239.1.194', port=808): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206C9AD0580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:21:32,220-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.242.246.156', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AD01C0>, 'Connection to 223.242.246.156 timed out. (connect timeout=10)'))
2019-12-19 06:21:42,234-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='59.57.149.8', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3E50>, 'Connection to 59.57.149.8 timed out. (connect timeout=10)'))
2019-12-19 06:21:52,252-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.18.61', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AE3A60>, 'Connection to 223.198.18.61 timed out. (connect timeout=10)'))
2019-12-19 06:21:54,560-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.7.100', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206C9B00C10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:22:04,577-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.164.238.209', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C9AEF580>, 'Connection to 183.164.238.209 timed out. (connect timeout=10)'))
2019-12-19 06:22:14,591-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.69.153.185', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000206C923BA30>, 'Connection to 117.69.153.185 timed out. (connect timeout=10)'))
2019-12-19 06:22:25,681-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.22.241', port=9999): Read timed out. (read timeout=10)
2019-12-19 06:22:25,682-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:22:25,900-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:22:28,103-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE37C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:22:38,118-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00370>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:22:48,138-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00F40>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:22:49,616-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:22:49,838-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:22:52,033-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00CD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:23:02,047-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D00>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:23:12,063-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268970>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:23:13,030-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:23:13,254-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:23:18,907-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:23:28,924-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00580>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:23:38,942-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7400>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:23:39,787-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:23:39,975-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:23:42,178-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:23:52,192-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268DC0>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:24:02,206-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3E80>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:24:02,781-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:24:02,982-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:24:06,620-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:24:16,636-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00FD0>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:24:26,656-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF580>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:24:27,273-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:24:27,497-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:24:29,675-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:24:39,689-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00880>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:24:49,703-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3BB0>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:24:50,272-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:24:50,469-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:24:52,670-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:25:02,687-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00550>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:25:12,709-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF880>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:25:13,993-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:25:14,199-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:25:16,400-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF6A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:25:26,418-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B20>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:25:36,436-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3430>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:25:38,897-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:25:39,100-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:25:41,321-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='sanshengny.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE39D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:25:51,337-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='sanshengny.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00D30>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:26:01,349-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='sanshengny.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF070>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:26:02,184-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:26:02,398-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:26:04,606-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='qixuanbaby.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:26:14,624-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='qixuanbaby.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B001C0>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:26:24,645-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='qixuanbaby.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D90>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:26:27,489-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:26:27,700-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:26:29,882-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:26:39,900-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B005E0>, 'Connection to 182.108.44.222 timed out. (connect timeout=10)'))
2019-12-19 06:26:49,913-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF850>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:26:59,929-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DFA0>, 'Connection to 180.122.51.24 timed out. (connect timeout=10)'))
2019-12-19 06:27:09,947-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00430>, 'Connection to 183.166.132.200 timed out. (connect timeout=10)'))
2019-12-19 06:27:19,966-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3EE0>, 'Connection to 117.88.5.126 timed out. (connect timeout=10)'))
2019-12-19 06:27:29,979-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268F40>, 'Connection to 111.79.45.87 timed out. (connect timeout=10)'))
2019-12-19 06:27:39,992-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7160>, 'Connection to 113.12.73.163 timed out. (connect timeout=10)'))
2019-12-19 06:27:50,005-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00220>, 'Connection to 117.82.248.126 timed out. (connect timeout=10)'))
2019-12-19 06:27:52,223-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF100>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:28:02,240-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFDF0>, 'Connection to 36.6.146.162 timed out. (connect timeout=10)'))
2019-12-19 06:28:04,444-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:28:14,460-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D60>, 'Connection to 182.35.85.125 timed out. (connect timeout=10)'))
2019-12-19 06:28:24,480-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268910>, 'Connection to 183.166.138.230 timed out. (connect timeout=10)'))
2019-12-19 06:28:34,494-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B000A0>, 'Connection to 117.69.201.158 timed out. (connect timeout=10)'))
2019-12-19 06:28:44,511-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B20>, 'Connection to 223.198.20.243 timed out. (connect timeout=10)'))
2019-12-19 06:28:46,811-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFFA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:28:56,826-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFFA0>, 'Connection to 111.79.45.5 timed out. (connect timeout=10)'))
2019-12-19 06:29:06,844-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE37C0>, 'Connection to 117.57.91.131 timed out. (connect timeout=10)'))
2019-12-19 06:29:16,864-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B007F0>, 'Connection to 112.85.163.146 timed out. (connect timeout=10)'))
2019-12-19 06:29:26,883-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268970>, 'Connection to 117.28.97.65 timed out. (connect timeout=10)'))
2019-12-19 06:29:36,902-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00550>, 'Connection to 183.166.163.164 timed out. (connect timeout=10)'))
2019-12-19 06:29:36,902-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:29:37,139-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:29:47,152-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B000A0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:29:49,334-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:29:49,543-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:29:59,556-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFB50>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:30:04,223-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:30:04,423-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:30:14,435-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A90>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:30:16,626-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:30:16,787-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:30:26,806-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B009A0>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:30:36,828-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3FD0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:30:46,846-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF490>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:30:56,866-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923B6A0>, 'Connection to 223.198.6.146 timed out. (connect timeout=10)'))
2019-12-19 06:30:59,085-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:31:09,098-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3280>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:31:19,118-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268B80>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:31:29,203-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:31:31,379-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:31:41,394-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923B280>, 'Connection to 114.226.162.7 timed out. (connect timeout=10)'))
2019-12-19 06:31:51,409-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFD90>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:32:01,426-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF8B0>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:32:11,446-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE36A0>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 06:32:21,466-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00BE0>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:32:25,202-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:32:25,423-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:32:35,436-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B007F0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:32:37,622-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:32:38,728-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:32:48,741-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BD00>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:32:58,755-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BD00>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:33:08,770-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE36A0>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:33:18,783-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B80>, 'Connection to 223.198.6.146 timed out. (connect timeout=10)'))
2019-12-19 06:33:20,991-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B004F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:33:31,007-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFA00>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:33:41,028-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3C10>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:33:51,049-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3F40>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 06:33:53,240-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFF70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:34:03,259-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF490>, 'Connection to 114.226.162.7 timed out. (connect timeout=10)'))
2019-12-19 06:34:13,278-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00E20>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:34:23,298-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE39A0>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:34:33,316-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3460>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 06:34:43,337-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923B6A0>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:34:46,825-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:34:47,050-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:34:57,063-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268BE0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:34:59,283-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFA60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:35:09,454-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:35:19,472-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7F40>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:35:29,492-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3FA0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:35:31,794-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:35:41,879-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:35:44,105-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:35:54,122-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF520>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:36:04,135-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00970>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:36:14,147-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF5E0>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 06:36:16,334-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:36:18,512-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3DC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:36:28,532-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3B80>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:36:38,549-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7160>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:36:48,562-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B004F0>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 06:36:58,578-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFC70>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:36:59,836-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:37:00,076-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:37:10,089-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF7C0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:37:12,274-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:37:12,409-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:37:22,428-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B006D0>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:37:35,557-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:37:35,792-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:37:39,611-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:37:41,823-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:37:41,954-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:37:51,967-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B80>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:38:01,985-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00760>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:38:04,298-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFF40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:38:11,751-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:38:21,769-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFE80>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 06:38:31,782-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A76A0>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:38:41,797-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3310>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:38:51,813-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B006D0>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 06:38:54,022-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:38:56,210-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BE80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:39:06,227-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DF70>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:39:16,246-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268DC0>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:39:26,265-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BA30>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 06:39:36,278-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF640>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:39:43,933-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:39:44,158-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:39:54,171-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D60>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:39:56,369-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B000A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:39:56,507-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:40:06,521-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00D90>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:40:16,589-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:40:18,905-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:40:21,217-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:40:31,233-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3820>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 06:40:41,254-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3220>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:40:51,272-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00460>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:41:01,292-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00D60>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 06:41:03,486-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF8B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:41:05,656-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:41:15,677-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00F40>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:41:25,697-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3970>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:41:35,710-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00BE0>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 06:41:45,726-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7D60>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:41:48,085-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:41:56,348-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:41:56,564-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:42:06,577-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268C70>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:42:08,765-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BCD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:42:09,927-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:42:19,942-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B000D0>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:42:29,959-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B004F0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:42:39,976-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7370>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:42:42,285-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:42:52,305-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3130>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 06:43:02,319-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3E80>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:43:12,335-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268B80>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:43:22,354-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00940>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 06:43:24,539-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BC70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:43:26,721-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFFA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:43:36,733-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3970>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:43:46,748-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3940>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:43:48,966-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B002B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:43:58,983-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00700>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:44:12,313-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:44:12,538-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:44:22,551-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF760>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:44:39,615-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:44:39,758-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:44:43,386-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:44:43,614-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:44:53,628-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF790>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:44:57,001-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:44:57,426-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:45:07,440-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268D30>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:45:11,505-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:45:11,740-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:45:21,752-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ymrfs8.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D60>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:45:28,420-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:45:28,644-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:45:38,657-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='lashowme8899.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3880>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:45:42,296-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:45:42,518-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:45:52,530-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='gber88.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268BB0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:45:54,182-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:45:54,387-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:46:04,400-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='haopeng.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF0D0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:46:05,502-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:46:05,703-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:46:15,716-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop11r05m7511231.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00160>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:46:17,424-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:46:17,639-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:46:27,652-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='aomeifen.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92689A0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:46:29,607-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:46:29,821-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:46:39,834-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1409676263726.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7400>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:46:42,022-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1409676263726.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00790>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:46:42,498-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1409676263726.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:46:46,101-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:46:46,316-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:46:56,327-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0d530684i2349.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3B20>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:46:58,550-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0d530684i2349.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DFA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:46:58,709-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0d530684i2349.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:46:59,916-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:47:00,136-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:47:10,151-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF6D0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:47:12,328-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:47:12,497-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:47:22,518-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268D90>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:47:32,531-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B80>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:47:42,547-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yazhimeineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF760>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:47:46,164-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:47:46,380-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:47:56,393-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0120i7w111035.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00130>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:48:06,409-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0120i7w111035.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3D90>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:48:09,554-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop0120i7w111035.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:48:10,682-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:48:10,912-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:48:20,926-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yangtingcc.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF3D0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:48:30,947-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yangtingcc.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7B80>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:48:31,079-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yangtingcc.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:48:34,214-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:48:34,428-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:48:44,440-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7AC0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:48:54,455-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFE80>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:48:54,595-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:48:56,815-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:48:57,031-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:49:07,044-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00D00>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:49:17,060-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7220>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:49:17,192-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:49:27,213-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A90>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:49:37,232-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE34C0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:49:47,252-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268B20>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:49:50,347-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:49:50,562-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:50:00,575-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF100>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:50:10,594-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923B8E0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:50:20,612-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='meidonglineiyi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFBB0>, 'Connection to 183.154.48.254 timed out. (connect timeout=10)'))
2019-12-19 06:50:21,793-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:50:22,027-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:50:32,039-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00FA0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:50:42,054-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3460>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:50:44,221-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop213n1nl7m4497.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE36A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:50:46,307-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:50:46,523-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:50:56,537-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE31F0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:51:06,556-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B008B0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:51:08,719-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1459443977551.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:51:09,347-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:51:09,572-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:51:19,585-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF220>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:51:29,600-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268A30>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:51:31,774-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='guangai2014.1688.com', port=443): Max retries exceeded with url: /?tracelog=p4p/page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE39D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:51:41,075-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:51:41,279-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:51:51,292-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF400>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:52:01,308-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3DC0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:52:03,474-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492102705496.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B003A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:52:11,160-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:52:11,401-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:52:21,430-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE38E0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:52:31,445-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF8E0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:52:33,614-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:52:41,179-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268D60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:52:51,190-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF8E0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:53:01,204-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE38E0>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:53:03,514-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:53:13,532-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A00>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 06:53:23,545-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF760>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 06:53:33,560-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268970>, 'Connection to 183.166.139.81 timed out. (connect timeout=10)'))
2019-12-19 06:53:35,758-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:53:37,988-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:53:48,004-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3F40>, 'Connection to 114.226.162.7 timed out. (connect timeout=10)'))
2019-12-19 06:53:58,023-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE38B0>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 06:54:08,042-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3AC0>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 06:54:10,239-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFD00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:54:20,254-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A74C0>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 06:54:22,554-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:54:33,658-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:54:43,682-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFB20>, 'Connection to 60.167.22.119 timed out. (connect timeout=10)'))
2019-12-19 06:54:53,695-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3E20>, 'Connection to 180.122.145.37 timed out. (connect timeout=10)'))
2019-12-19 06:55:03,779-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:55:13,791-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1492707389488.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE31F0>, 'Connection to 36.25.42.171 timed out. (connect timeout=10)'))
2019-12-19 06:55:13,792-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:55:14,025-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:55:16,266-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='sanshengny.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A75E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:55:26,283-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='sanshengny.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF490>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:55:27,328-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:55:27,540-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:55:37,553-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='qixuanbaby.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF7F0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:55:47,569-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='qixuanbaby.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE36A0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:55:48,494-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:55:48,718-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:55:58,730-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFCA0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:56:08,748-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='daimushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00EE0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:56:09,776-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:56:09,988-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:56:20,001-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00040>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:56:30,018-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF6A0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:56:30,317-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:56:32,507-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268DC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:56:42,527-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='zimengshibra.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DA90>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:56:43,916-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:56:44,129-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:56:54,143-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7BB0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:57:04,160-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B005B0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:57:04,462-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:57:06,600-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE38B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:57:19,659-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1466442490958.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-12-19 06:57:21,217-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:57:21,442-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:57:31,455-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00910>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:57:41,476-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DA90>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:57:41,671-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:57:43,828-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:57:53,844-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B006A0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:58:03,859-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1451580478268.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3F70>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:58:07,044-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:58:07,257-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:58:17,269-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF6D0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:58:27,286-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF0A0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:58:27,939-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:58:30,110-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00790>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:58:40,127-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268F70>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:58:50,147-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ttnysh.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B005B0>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:58:51,625-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:58:51,834-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:59:01,847-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF190>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 06:59:11,868-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3880>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:59:12,032-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 06:59:22,052-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3340>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 06:59:32,072-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00D90>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 06:59:42,091-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1458233208347.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268A30>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 06:59:43,521-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:59:43,736-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:59:53,749-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B50>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 07:00:03,767-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFFA0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:00:04,025-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-12-19 07:00:14,043-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A60>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 07:00:24,063-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3850>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 07:00:34,082-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF880>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 07:00:36,436-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:00:46,455-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268D90>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 07:00:56,467-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A76A0>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 07:00:58,656-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFB20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:01:08,673-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE39A0>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 07:01:10,874-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7100>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:01:13,050-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF760>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:01:23,064-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268B20>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 07:01:33,081-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1488992294723.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3850>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 07:01:48,626-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:01:48,854-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:01:58,868-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00730>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 07:02:08,884-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF700>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:02:14,318-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF7F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:02:24,334-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A72E0>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 07:02:34,352-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3100>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 07:02:44,371-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00640>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 07:02:47,127-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268340>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:02:57,142-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B008B0>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 07:03:07,158-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF9D0>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 07:03:09,370-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:03:19,386-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A71F0>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 07:03:21,591-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3100>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:03:23,779-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:03:33,798-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00F40>, 'Connection to 60.167.132.249 timed out. (connect timeout=10)'))
2019-12-19 07:03:43,818-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268F70>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 07:03:55,782-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1091: The handshake operation timed out')))
2019-12-19 07:04:05,799-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='ywmzm.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7430>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 07:04:07,075-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:04:07,299-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:04:09,745-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:04:19,761-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFC10>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:04:21,948-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='xzr668.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:04:23,713-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:04:23,923-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:04:26,403-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:04:36,423-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00C40>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:04:38,605-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1436893643475.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:04:49,790-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:04:52,034-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:04:54,495-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:05:04,509-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF040>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:05:06,776-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:05:16,791-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268E50>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 07:05:26,807-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00160>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 07:05:36,827-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00B50>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 07:05:39,136-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C8E7DF70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:05:49,156-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF910>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 07:05:59,175-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3520>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 07:06:01,383-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:06:11,402-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268E50>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 07:06:13,616-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:06:15,800-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00340>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:06:23,401-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEF8B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:06:33,414-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7430>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 07:06:35,599-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:06:45,618-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1419266664228.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3A00>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 07:06:49,787-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:06:49,991-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:07:00,005-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFEE0>, 'Connection to 183.164.238.205 timed out. (connect timeout=10)'))
2019-12-19 07:07:10,022-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B003D0>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 07:07:12,182-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:07:22,202-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92A7280>, 'Connection to 112.85.125.33 timed out. (connect timeout=10)'))
2019-12-19 07:07:32,221-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C923BEE0>, 'Connection to 210.5.10.87 timed out. (connect timeout=10)'))
2019-12-19 07:07:42,240-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE38E0>, 'Connection to 223.198.26.52 timed out. (connect timeout=10)'))
2019-12-19 07:07:44,541-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:07:54,559-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9268B20>, 'Connection to 183.166.138.199 timed out. (connect timeout=10)'))
2019-12-19 07:08:04,578-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00100>, 'Connection to 117.88.177.109 timed out. (connect timeout=10)'))
2019-12-19 07:08:06,771-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00AC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:08:16,788-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00700>, 'Connection to 117.69.151.79 timed out. (connect timeout=10)'))
2019-12-19 07:08:19,147-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C92682B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:08:21,386-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:08:23,588-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AE3BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 07:08:33,603-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00430>, 'Connection to 223.198.23.24 timed out. (connect timeout=10)'))
2019-12-19 07:08:43,622-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9AEFAC0>, 'Connection to 60.167.133.35 timed out. (connect timeout=10)'))
2019-12-19 07:08:53,643-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='yurunfushi.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000206C9B00370>, 'Connection to 223.198.20.251 timed out. (connect timeout=10)'))
2019-12-19 07:08:54,857-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:08:55,082-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:08:58,931-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:08:59,141-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:03,546-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:03,766-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:08,671-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:08,890-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:12,911-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:13,123-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:15,474-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:15,707-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:18,791-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:19,006-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:23,255-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:23,471-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:25,615-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:25,837-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:28,990-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:29,187-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:36,663-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 07:09:36,867-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 07:09:38,202-get_store_phone-177-INFO:>>>内衣-1576707518782.csv success
